import type { QuizQuestion as QuizDataQuestion } from '@/ai/schemas';

/**
 * @fileOverview Fallback quiz data source.
 * This file contains a curated list of high-quality questions used as a fallback
 * when the primary AI generation system fails or when Firestore is unavailable.
 */

// Helper to shuffle an array, used for local fallback.
export function shuffleArray<T>(array: T[]): T[] {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
    return array;
}

export type FallbackQuestion = Omit<QuizDataQuestion, 'id'> & { 
    format: string;
    difficulty: 'Easy' | 'Medium' | 'Hard' | 'Very Hard' | 'Expert';
    hint: string;
};

// A smaller, local fallback in case Firestore fails.
export const allFallbackQuestions: FallbackQuestion[] = [
    // =================================================================================
    // MIXED (1000 Questions)
    // =================================================================================
    // Easy
    { format: 'mixed', difficulty: 'Easy', question: 'How many players are there on a standard cricket team?', options: ['9', '10', '11', '12'], correctAnswer: '11', explanation: 'A standard cricket team consists of eleven players on the field.', hint: 'It\'s one more than a standard soccer team.' },
    { format: 'mixed', difficulty: 'Easy', question: 'What is a "maiden over"?', options: ['An over with 1 wicket', 'An over with 6 wides', 'An over with no runs scored', 'An over bowled by a female cricketer'], correctAnswer: 'An over with no runs scored', explanation: 'A maiden over is an over in which the bowler does not concede any runs scored off the bat.', hint: 'Think about what "maiden" means in the context of being first or untouched.' },
    { format: 'mixed', difficulty: 'Easy', question: 'What does "LBW" stand for?', options: ['Leg Before Wicket', 'Leg Behind Wicket', 'Long Ball Wide', 'Leg Bye Wicket'], correctAnswer: 'Leg Before Wicket', explanation: 'LBW is a common way for a batsman to be dismissed if the ball strikes their body before the bat.', hint: 'The first word is "Leg".' },
    { format: 'mixed', difficulty: 'Easy', question: 'Which country is credited with inventing the game of cricket?', options: ['Australia', 'India', 'South Africa', 'England'], correctAnswer: 'England', explanation: 'Cricket is believed to have originated in south-east England in the 16th century.', hint: 'The country is famous for its monarchy and tea.' },
    { format: 'mixed', difficulty: 'Easy', question: 'What is the name of the trophy for the Test series between Australia and England?', options: ['The Border-Gavaskar Trophy', 'The Ashes', 'The Chappell-Hadlee Trophy', 'The Frank Worrell Trophy'], correctAnswer: 'The Ashes', explanation: 'The Ashes is a historic Test cricket series played between England and Australia, named after a satirical obituary published in 1882.', hint: 'It sounds like what\'s left after a fire.' },
    { format: 'mixed', difficulty: 'Easy', question: 'What is a "dot ball"?', options: ['A ball that hits the stumps', 'A ball from which no runs are scored', 'A ball that is bowled wide', 'A ball that is not timed well by the batsman'], correctAnswer: 'A ball from which no runs are scored', explanation: 'A dot ball is a delivery from which no runs are scored, recorded as a dot in the scorer\'s book.', hint: 'It\'s represented by a single point in the scorebook.' },
    { format: 'mixed', difficulty: 'Easy', question: 'What is a "no-ball"?', options: ['A ball that does not bounce', 'A ball that bounces too high', 'An illegal delivery', 'A ball the batsman misses'], correctAnswer: 'An illegal delivery', explanation: 'A no-ball is an illegal delivery, most commonly for overstepping the popping crease. The batting team gets a run and a free hit in limited overs.', hint: 'It results in a penalty and often a free hit.'},
    { format: 'mixed', difficulty: 'Easy', question: 'What is the term for hitting the ball for six runs?', options: ['Boundary', 'Maximum', 'Sixer', 'Homerun'], correctAnswer: 'Maximum', explanation: 'While often called a sixer, the technically correct term used by commentators for a six is a "maximum".', hint: 'Think of getting the highest possible score from one shot.'},
    { format: 'mixed', difficulty: 'Easy', question: 'The area of the field between point and cover is known as?', options: ['The slips', 'The gully', 'Cover point', 'Mid-wicket'], correctAnswer: 'Cover point', explanation: 'The area just behind point and to the side of cover is referred to as cover point.', hint: 'It\'s a combination of two fielding positions.'},
    { format: 'mixed', difficulty: 'Easy', question: 'What does the term "wicket-keeper" refer to?', options: ['The stumps', 'The bowler', 'The player behind the stumps', 'The captain'], correctAnswer: 'The player behind the stumps', explanation: 'The wicket-keeper is the specialist fielder who stands behind the batsman\'s wicket.', hint: 'This player wears gloves and pads.'},
    { format: 'mixed', difficulty: 'Easy', question: 'What is a "bouncer"?', options: ['A soft, loopy delivery', 'A ball that bounces twice', 'A short-pitched fast delivery', 'A ball that spins sharply'], correctAnswer: 'A short-pitched fast delivery', explanation: 'A bouncer is a short-pitched delivery that bounces high, usually aimed at the batsman\'s head or upper body.', hint: 'It\'s designed to intimidate the batsman with its height.'},
    { format: 'mixed', difficulty: 'Easy', question: 'What is a "free hit"?', options: ['The batsman can\'t be out', 'The batsman gets an extra run', 'A penalty shot for the batting side', 'The bowler can bowl from anywhere'], correctAnswer: 'A penalty shot for the batting side', explanation: 'Following certain types of no-balls in limited-overs cricket, the next delivery is a "free hit," where the batsman can only be dismissed by being run out.', hint: 'It follows an illegal delivery from the bowler.'},
    { format: 'mixed', difficulty: 'Easy', question: 'How many balls are there in a standard over?', options: ['4', '5', '6', '8'], correctAnswer: '6', explanation: 'A standard over in cricket consists of six legal deliveries bowled by one bowler.', hint: 'It\'s half a dozen.' },
    { format: 'mixed', difficulty: 'Easy', question: 'What is the name of the cricket ground in London often called the "Home of Cricket"?', options: ['The Oval', 'Edgbaston', 'Lord\'s', 'Old Trafford'], correctAnswer: 'Lord\'s', explanation: 'Lord\'s Cricket Ground in London is owned by the Marylebone Cricket Club (MCC) and is known worldwide as the "Home of Cricket".', hint: 'It is named after its founder, Thomas Lord.' },
    { format: 'mixed', difficulty: 'Easy', question: 'What is the term for a batsman scoring 100 runs?', options: ['Fifty', 'Ton', 'Century', 'Milestone'], correctAnswer: 'Century', explanation: 'Scoring 100 runs in a single innings is a significant achievement known as a century.', hint: 'It shares its name with a period of 100 years.' },
    { format: 'mixed', difficulty: 'Easy', question: 'Which piece of equipment is NOT worn by a batsman?', options: ['Helmet', 'Pads', 'Shin guards', 'Gloves'], correctAnswer: 'Shin guards', explanation: 'Batsmen wear pads to protect their legs, but shin guards are typically associated with sports like soccer.', hint: 'These are worn in soccer but not cricket.' },
    { format: 'mixed', difficulty: 'Easy', question: 'The long rectangular strip in the middle of the field is called the...?', options: ['Track', 'Runway', 'Pitch', 'Lane'], correctAnswer: 'Pitch', explanation: 'The pitch is the central strip of the cricket field where most of the action takes place.', hint: 'It\'s where the bowling and batting happens.' },
    { format: 'mixed', difficulty: 'Easy', question: 'What does it mean if a batsman is "run out"?', options: ['He ran too slowly', 'He hit the ball out of the park', 'His wicket is put down while he is out of his crease', 'He retired from the game'], correctAnswer: 'His wicket is put down while he is out of his crease', explanation: 'A batsman is run out if a fielder dislodges the bails while the batsman is attempting a run and is short of the crease.', hint: 'It involves a fielder hitting the stumps with the ball.' },
    { format: 'mixed', difficulty: 'Easy', question: 'In cricket, what is the term for a score of zero?', options: ['A blank', 'A miss', 'A duck', 'A ghost'], correctAnswer: 'A duck', explanation: 'A "duck" is the term for a batsman being dismissed without scoring any runs.', hint: 'It\'s named after a type of bird.'},
    { format: 'mixed', difficulty: 'Easy', question: 'Which format of cricket is the longest?', options: ['T20', 'One Day International', 'Test Cricket', 'The Hundred'], correctAnswer: 'Test Cricket', explanation: 'Test cricket is the longest format of the sport, with matches lasting up to five days.', hint: 'It is a "test" of endurance and skill.' },
    { format: 'mixed', difficulty: 'Easy', question: 'What is the fielding position directly behind the wicket-keeper called?', options: ['First Slip', 'Gully', 'Short Leg', 'Point'], correctAnswer: 'First Slip', explanation: 'The slip cordon is positioned to catch edges from the batsman, with first slip being the closest to the keeper.', hint: 'These fielders are waiting for an edge.' },
    { format: 'mixed', difficulty: 'Easy', question: 'What is a "wide" ball?', options: ['A ball that is too fast', 'A ball bowled too wide for the batsman to hit', 'A ball that bounces over the batsman\'s head', 'A ball that doesn\'t bounce'], correctAnswer: 'A ball bowled too wide for the batsman to hit', explanation: 'A wide is an illegal delivery that is judged by the umpire to be too wide of the batsman to be scored from.', hint: 'It results in an extra run and the ball being re-bowled.' },
    { format: 'mixed', difficulty: 'Easy', question: 'Which country is nicknamed the "Baggy Greens"?', options: ['South Africa', 'New Zealand', 'Australia', 'England'], correctAnswer: 'Australia', explanation: 'The Australian Test cricket team is famously known as the Baggy Greens, after their iconic cap.', hint: 'They are famous for their green and gold colors.' },
    { format: 'mixed', difficulty: 'Easy', question: 'How many umpires are on the field during a match?', options: ['1', '2', '3', '4'], correctAnswer: '2', explanation: 'There are two on-field umpires during a cricket match, one at the bowler\'s end and one at square leg.', hint: 'There is also a third umpire off the field.' },
    { format: 'mixed', difficulty: 'Easy', question: 'What is the role of the "12th Man"?', options: ['An extra umpire', 'A substitute fielder', 'An assistant coach', 'A water boy'], correctAnswer: 'A substitute fielder', explanation: 'The 12th man is a substitute who can field for an injured player but is not allowed to bat, bowl, or keep wicket.', hint: 'This player is part of the squad but not the starting XI.' },
    { format: 'mixed', difficulty: 'Easy', question: 'What does "DRS" stand for?', options: ['Direct Review System', 'Decision Review System', 'Digital Replay System', 'Dynamic Ruling System'], correctAnswer: 'Decision Review System', explanation: 'DRS allows teams to challenge the on-field umpire\'s decision with the help of technology.', hint: 'It\'s used to challenge an umpire\'s call.' },
    { format: 'mixed', difficulty: 'Easy', question: 'Which part of the bat is known as the "sweet spot"?', options: ['The edge', 'The toe', 'The middle', 'The handle'], correctAnswer: 'The middle', explanation: 'The middle of the bat is the thickest part and provides the most power when hitting the ball.', hint: 'It\'s the best place to hit the ball.' },
    { format: 'mixed', difficulty: 'Easy', question: 'What is a "hat-trick"?', options: ['Hitting three sixes in a row', 'A bowler taking three wickets in three balls', 'Scoring 300 runs', 'Winning three matches in a row'], correctAnswer: 'A bowler taking three wickets in three balls', explanation: 'A hat-trick is a rare and celebrated achievement where a bowler dismisses three batsmen with three consecutive deliveries.', hint: 'It\'s a bowler\'s dream achievement.' },
    { format: 'mixed', difficulty: 'Easy', question: 'What is the term for the two pieces of wood that sit on top of the stumps?', options: ['Bails', 'Tops', 'Caps', 'Lids'], correctAnswer: 'Bails', explanation: 'The two small pieces of wood placed on top of the three stumps are called bails.', hint: 'The wicket is broken when these are dislodged.' },
    { format: 'mixed', difficulty: 'Easy', question: 'Which fielding position is deep on the leg side boundary?', options: ['Deep Cover', 'Long On', 'Deep Square Leg', 'Third Man'], correctAnswer: 'Deep Square Leg', explanation: 'Deep Square Leg is a boundary fielding position on the leg side, roughly level with the batsman\'s crease.', hint: 'It\'s on the same side as the batsman\'s legs.' },
    { format: 'mixed', difficulty: 'Easy', question: 'What is the name of the main cricket governing body?', options: ['FIFA', 'ICC', 'IOC', 'NBA'], correctAnswer: 'ICC', explanation: 'The International Cricket Council (ICC) is the world governing body of cricket.', hint: 'It stands for International Cricket Council.' },
    { format: 'mixed', difficulty: 'Easy', question: 'What is a "yorker"?', options: ['A slow, loopy ball', 'A ball aimed at the batsman\'s toes', 'A very short ball', 'A ball that doesn\'t bounce'], correctAnswer: 'A ball aimed at the batsman\'s toes', explanation: 'A yorker is a delivery bowled right at the base of the stumps or the batsman\'s feet, making it difficult to hit.', hint: 'It\'s meant to go under the bat.' },
    { format: 'mixed', difficulty: 'Easy', question: 'What is a "full toss"?', options: ['A ball that bounces twice', 'A ball that doesn\'t bounce', 'A very slow ball', 'A ball that hits the helmet'], correctAnswer: 'A ball that doesn\'t bounce', explanation: 'A full toss is a delivery that reaches the batsman without bouncing on the pitch.', hint: 'It can be easy to hit if not bowled well.' },
    { format: 'mixed', difficulty: 'Easy', question: 'What is the crease line in front of the stumps called?', options: ['Bowling crease', 'Popping crease', 'Return crease', 'Boundary crease'], correctAnswer: 'Popping crease', explanation: 'The popping crease (or batting crease) is the line a batsman must have some part of their body or bat behind to be safe from being stumped or run out.', hint: 'Batsmen must stay behind this line.' },
    { format: 'mixed', difficulty: 'Easy', question: 'What is the term when a bowler bowls an over without conceding any runs?', options: ['Clean Over', 'Maiden Over', 'Zero Over', 'Perfect Over'], correctAnswer: 'Maiden Over', explanation: 'A maiden over is an over in which no runs are scored off the bat, a fine achievement for a bowler.', hint: 'This term suggests purity or being untouched.' },
    { format: 'mixed', difficulty: 'Easy', question: 'How many runs are scored for hitting the ball directly over the boundary rope?', options: ['2', '4', '6', '8'], correctAnswer: '6', explanation: 'A batsman scores six runs if they hit the ball over the boundary on the full.', hint: 'It\'s also called a "maximum".' },
    { format: 'mixed', difficulty: 'Easy', question: 'What is the term for a batsman being dismissed on their very first ball?', options: ['Silver Duck', 'Platinum Duck', 'Golden Duck', 'Diamond Duck'], correctAnswer: 'Golden Duck', explanation: 'A Golden Duck is the unfortunate dismissal of a batsman from the first delivery they face.', hint: 'It\'s named after a precious metal.' },
    { format: 'mixed', difficulty: 'Easy', question: 'The fielding position "silly point" is located where?', options: ['Deep on the boundary', 'Very close to the batsman', 'Behind the wicket-keeper', 'Next to the bowler'], correctAnswer: 'Very close to the batsman', explanation: 'Silly point is a dangerous fielding position very close to the batsman on the off-side, requiring a helmet and a lot of courage.', hint: 'It\'s considered a "silly" place to stand because of the risk.' },
    { format: 'mixed', difficulty: 'Easy', question: 'Which team is known as the "Proteas"?', options: ['New Zealand', 'South Africa', 'Sri Lanka', 'Pakistan'], correctAnswer: 'South Africa', explanation: 'The South African national cricket team is nicknamed the Proteas, after the country\'s national flower.', hint: 'Their nickname comes from a flower.' },
    { format: 'mixed', difficulty: 'Easy', question: 'What is a "switch hit"?', options: ['Hitting the ball with the back of the bat', 'Changing stance from right to left-handed (or vice versa) to hit the ball', 'Hitting the stumps with the bat', 'A type of defensive shot'], correctAnswer: 'Changing stance from right to left-handed (or vice versa) to hit the ball', explanation: 'A switch hit is an audacious modern shot where a batsman changes their grip and stance to that of the opposite handedness as the bowler is running in.', hint: 'It involves changing your batting hand.' },
    { format: 'mixed', difficulty: 'Easy', question: 'What is a "half-volley"?', options: ['A ball that bounces at the batsman\'s feet', 'A very short ball', 'A delivery that is pitched up and easy to drive', 'A slower ball'], correctAnswer: 'A delivery that is pitched up and easy to drive', explanation: 'A half-volley is a delivery that is pitched slightly fuller than a good length, making it an ideal length to hit a drive.', hint: 'It\'s a batsman\'s favorite delivery to drive.' },
    { format: 'mixed', difficulty: 'Easy', question: 'What is a "googly"?', options: ['A fast, swinging delivery', 'A left-arm spinner\'s stock ball', 'A leg-spinner\'s deceptive delivery that spins the other way', 'A very high bouncer'], correctAnswer: 'A leg-spinner\'s deceptive delivery that spins the other way', explanation: 'A googly, or wrong\'un, is a deceptive delivery from a leg-spin bowler that spins from the off side to the leg side for a right-handed batsman.', hint: 'It\'s a leg-spinner\'s surprise weapon.' },
    { format: 'mixed', difficulty: 'Easy', question: 'Which team is nicknamed the "Black Caps"?', options: ['Australia', 'South Africa', 'England', 'New Zealand'], correctAnswer: 'New Zealand', explanation: 'The New Zealand national cricket team is known as the Black Caps.', hint: 'Their uniform is predominantly black.' },
    { format: 'mixed', difficulty: 'Easy', question: 'How many runs are awarded for a "no-ball"?', options: ['0', '1', '2', '4'], correctAnswer: '1', explanation: 'One run is awarded to the batting team for a no-ball, and the ball must be bowled again. Any runs scored off the bat are also added.', hint: 'It\'s a penalty run.' },
    { format: 'mixed', difficulty: 'Easy', question: 'What is the "third man" fielding position?', options: ['A position behind the bowler', 'A position behind the wicket-keeper on the off-side', 'A position deep on the leg-side', 'An extra umpire'], correctAnswer: 'A position behind the wicket-keeper on the off-side', explanation: 'Third man is a fielding position on the off-side, behind the wicket-keeper and slip fielders, often near the boundary.', hint: 'It\'s behind the batsman on the off side.' },
    { format: 'mixed', difficulty: 'Easy', question: 'What is the term for a period of play between two breaks?', options: ['A quarter', 'A period', 'A half', 'A session'], correctAnswer: 'A session', explanation: 'A day\'s play in Test cricket is divided into three sessions: morning, afternoon, and evening, separated by lunch and tea breaks.', hint: 'A Test match day has three of these.' },
    { format: 'mixed', difficulty: 'Easy', question: 'What is a "reverse swing"?', options: ['Swing that happens early in the innings', 'Swing that goes in the opposite direction to conventional swing', 'A type of spin bowling', 'A slow, swinging delivery'], correctAnswer: 'Swing that goes in the opposite direction to conventional swing', explanation: 'Reverse swing is a phenomenon where an old, worn cricket ball swings in the opposite direction to how a new ball would swing.', hint: 'It\'s a skill often mastered by bowlers from the subcontinent.' },
    { format: 'mixed', difficulty: 'Easy', question: 'What is a "powerplay" in limited-overs cricket?', options: ['A period where only two fielders are allowed outside the circle', 'When a special, harder ball is used', 'A 5-minute break', 'A chance to review an umpire\'s decision'], correctAnswer: 'A period where only two fielders are allowed outside the circle', explanation: 'Powerplays are phases of an innings where fielding restrictions are in place to encourage attacking batting.', hint: 'It restricts the number of fielders in the outfield.' },
    { format: 'mixed', difficulty: 'Easy', question: 'What is the main role of a "nightwatchman"?', options: ['To score runs quickly at the end of the day', 'To protect a better batsman by batting at the end of a day\'s play', 'A security guard', 'An umpire who officiates at night'], correctAnswer: 'To protect a better batsman by batting at the end of a day\'s play', explanation: 'In Test cricket, a nightwatchman is a lower-order batsman sent in to bat near the close of play to shield a more valuable batsman from dismissal.', hint: 'This player is a sacrificial pawn.' },
    { format: 'mixed', difficulty: 'Easy', question: 'What is a "blockhole"?', options: ['A hole in the bat', 'The area on the pitch where a yorker is aimed', 'A defensive fielding position', 'A gap in the field'], correctAnswer: 'The area on the pitch where a yorker is aimed', explanation: 'The blockhole is the area on the pitch at the batsman\'s feet, which is the target for a yorker delivery.', hint: 'It\'s where a batsman would place their bat to block a full ball.' },
    
    // Medium
    { format: 'mixed', difficulty: 'Medium', question: 'What is the term for a score of 111 in cricket?', options: ['Century', 'Duckworth', 'Nelson', 'Hat-trick'], correctAnswer: 'Nelson', explanation: 'A score of 111 is known as a "Nelson" in cricket, a superstition in the game.', hint: 'It\'s named after a famous British admiral with one eye and one arm.' },
    { format: 'mixed', difficulty: 'Medium', question: 'The "DLS" method is used for calculating revised targets in which type of matches?', options: ['Test matches', 'First-class matches', 'Rain-affected limited-overs matches', 'Charity matches'], correctAnswer: 'Rain-affected limited-overs matches', explanation: 'The Duckworth-Lewis-Stern (DLS) method is a mathematical formula used to set a fair target in a limited-overs match interrupted by weather.', hint: 'This method is only needed when time is lost and overs are reduced.' },
    { format: 'mixed', difficulty: 'Medium', question: 'Who was the first batsman to score 10,000 runs in Test cricket?', options: ['Don Bradman', 'Sunil Gavaskar', 'Viv Richards', 'Allan Border'], correctAnswer: 'Sunil Gavaskar', explanation: 'India\'s Sunil Gavaskar was the first cricketer to reach the milestone of 10,000 runs in Test matches.', hint: 'He was an Indian opening batsman known as the "Little Master".' },
    { format: 'mixed', difficulty: 'Medium', question: 'What is a "Mankad" dismissal?', options: ['Hitting the wicket with a throw', 'A bowler running out the non-striker before bowling', 'A batsman obstructing the field', 'A type of catch'], correctAnswer: 'A bowler running out the non-striker before bowling', explanation: 'Mankading is when a bowler runs out the non-striking batsman for backing up too far before the ball is delivered. It is named after Vinoo Mankad.', hint: 'It involves the non-striker\'s crease.'},
    { format: 'mixed', difficulty: 'Medium', question: 'Who invented the "doosra"?', options: ['Muttiah Muralitharan', 'Saqlain Mushtaq', 'Harbhajan Singh', 'Shane Warne'], correctAnswer: 'Saqlain Mushtaq', explanation: 'Pakistani off-spinner Saqlain Mushtaq is credited with the invention of the "doosra," an off-spinner\'s delivery that spins away from the right-handed batsman.', hint: 'He was a Pakistani off-spinner in the 90s and 2000s.'},
    { format: 'mixed', difficulty: 'Medium', question: 'Which player is nicknamed "The Wall"?', options: ['Sachin Tendulkar', 'Rahul Dravid', 'VVS Laxman', 'Anil Kumble'], correctAnswer: 'Rahul Dravid', explanation: 'Rahul Dravid was known for his solid defensive technique and concentration, earning him the nickname "The Wall".', hint: 'This Indian batsman was known for his incredible defence.'},
    { format: 'mixed', difficulty: 'Medium', question: 'In which year were fielding restrictions first introduced in ODIs?', options: ['1975', '1980', '1992', '2001'], correctAnswer: '1992', explanation: 'Fielding restrictions, limiting the number of fielders outside the 30-yard circle, were formally introduced in the 1992 World Cup.', hint: 'This was the same World Cup that featured colored clothing and white balls for the first time.'},
    { format: 'mixed', difficulty: 'Medium', question: 'What is the weight of a standard cricket ball?', options: ['142g to 149g', '156g to 163g', '170g to 177g', '180g to 185g'], correctAnswer: '156g to 163g', explanation: 'A standard cricket ball for men\'s cricket must weigh between 5.5 and 5.75 ounces (155.9g and 163g).', hint: 'It weighs a little over 5.5 ounces.'},
    { format: 'mixed', difficulty: 'Medium', question: 'The "Ball of the Century" was bowled by Shane Warne to which batsman?', options: ['Sachin Tendulkar', 'Mike Gatting', 'Brian Lara', 'Graham Gooch'], correctAnswer: 'Mike Gatting', explanation: 'Shane Warne\'s first delivery in Ashes cricket in 1993 drifted and spun extravagantly to bowl England\'s Mike Gatting.', hint: 'The batsman was an English player with a notable physique.' },
    { format: 'mixed', difficulty: 'Medium', question: 'Who holds the record for the most catches by a non-wicketkeeper in Test cricket?', options: ['Ricky Ponting', 'Jacques Kallis', 'Mahela Jayawardene', 'Rahul Dravid'], correctAnswer: 'Rahul Dravid', explanation: 'India\'s Rahul Dravid holds the world record for the most catches in Test cricket by a non-wicketkeeper, with 210 catches.', hint: 'This Indian batsman was also known as "The Wall".'},
    { format: 'mixed', difficulty: 'Medium', question: 'What is the term for a batsman scoring fifty runs?', options: ['Quarter-century', 'Half-century', 'Fifty-run stand', 'Half-ton'], correctAnswer: 'Half-century', explanation: 'A score of 50 runs by a batsman is called a half-century, a significant milestone in an innings.', hint: 'It\'s half of a major batting milestone.' },
    { format: 'mixed', difficulty: 'Medium', question: 'Which bowler was the first to take 400 wickets in Test cricket?', options: ['Ian Botham', 'Kapil Dev', 'Richard Hadlee', 'Dennis Lillee'], correctAnswer: 'Richard Hadlee', explanation: 'New Zealand\'s Sir Richard Hadlee was the first bowler to reach the milestone of 400 Test wickets in 1990.', hint: 'This legendary all-rounder was from New Zealand.' },
    { format: 'mixed', difficulty: 'Medium', question: 'What is the "UDRS"?', options: ['Umpire\'s Direct Ruling System', 'Underarm Delivery Ruling System', 'Umpire Decision Review System', 'Universal DRS'], correctAnswer: 'Umpire Decision Review System', explanation: 'The Umpire Decision Review System (UDRS or DRS) is the official name for the technology-based system used to review on-field decisions.', hint: 'It\'s the official name for the system that uses Hawk-Eye and other technology.' },
    { format: 'mixed', difficulty: 'Medium', question: 'A "dibbly-dobbly" bowler is known for what?', options: ['Extreme pace', 'Sharp spin', 'Lack of pace but accurate and tricky', 'Bowling underarm'], correctAnswer: 'Lack of pace but accurate and tricky', explanation: 'A "dibbly-dobbly" bowler is a medium-pacer who lacks outright speed but relies on accuracy, subtle swing or seam, and changes of pace to get wickets.', hint: 'Think of a bowler who is not fast but very clever.' },
    { format: 'mixed', difficulty: 'Medium', question: 'In cricket, what does "sledging" refer to?', options: ['Polishing the ball', 'Appealing loudly', 'Verbally intimidating or taunting an opponent', 'Celebrating a wicket'], correctAnswer: 'Verbally intimidating or taunting an opponent', explanation: 'Sledging is the practice of verbally unsettling a batsman to disrupt their concentration, often through witty or insulting remarks.', hint: 'It\'s the "mental disintegration" part of the game.' },
    { format: 'mixed', difficulty: 'Medium', question: 'Who holds the record for the most sixes in an ODI innings?', options: ['Rohit Sharma', 'Chris Gayle', 'AB de Villiers', 'Eoin Morgan'], correctAnswer: 'Eoin Morgan', explanation: 'Eoin Morgan, playing for England, hit a record 17 sixes in his innings of 148 against Afghanistan in the 2019 World Cup.', hint: 'This English captain set the record in the 2019 World Cup.' },
    { format: 'mixed', difficulty: 'Medium', question: 'What is a "Flipper" in spin bowling?', options: ['A top-spinner', 'A leg-break that skids on with underspin', 'An off-break from a leg-spinner', 'A faster ball'], correctAnswer: 'A leg-break that skids on with underspin', explanation: 'The flipper is a delivery from a wrist-spinner that is squeezed out of the front of the hand, resulting in underspin that causes the ball to skid on low and fast.', hint: 'It\'s a deceptive delivery from a wrist-spinner that stays low.' },
    { format: 'mixed', difficulty: 'Medium', question: 'Which stadium is known as "The Gabba"?', options: ['Sydney Cricket Ground', 'Adelaide Oval', 'Brisbane Cricket Ground', 'Melbourne Cricket Ground'], correctAnswer: 'Brisbane Cricket Ground', explanation: 'The Brisbane Cricket Ground is commonly known as The Gabba, located in the suburb of Woolloongabba.', hint: 'It\'s located in Brisbane, Australia.' },
    { format: 'mixed', difficulty: 'Medium', question: 'Who was the first captain to win the ICC Champions Trophy?', options: ['Hansie Cronje', 'Steve Waugh', 'Arjuna Ranatunga', 'Brian Lara'], correctAnswer: 'Hansie Cronje', explanation: 'South Africa, under the captaincy of Hansie Cronje, won the inaugural edition of the tournament (then called the Wills International Cup) in 1998.', hint: 'He was a South African captain in the 90s.' },
    { format: 'mixed', difficulty: 'Medium', question: 'What is the "carrom ball"?', options: ['A ball bowled with the knuckles', 'A type of bouncer', 'A finger-flicked delivery that can spin either way', 'A very slow looping delivery'], correctAnswer: 'A finger-flicked delivery that can spin either way', explanation: 'The carrom ball is a mystery spin delivery where the bowler flicks the ball with their middle finger, making it behave unpredictably.', hint: 'It is flicked like a piece in the board game of the same name.' },
    
    // Hard
    { format: 'mixed', difficulty: 'Hard', question: 'Who is the only player to score 400 runs in a single Test innings?', options: ['Don Bradman', 'Virender Sehwag', 'Chris Gayle', 'Brian Lara'], correctAnswer: 'Brian Lara', explanation: 'Brian Lara of the West Indies scored an unbeaten 400 against England in 2004, the only quadruple century in Test history.', hint: 'This left-handed West Indian legend holds many batting records.' },
    { format: 'mixed', difficulty: 'Hard', question: 'The first official international cricket match was held in 1844 between which two nations?', options: ['England and Australia', 'USA and Canada', 'India and England', 'South Africa and Australia'], correctAnswer: 'USA and Canada', explanation: 'The first-ever officially recognized international cricket match took place between the United States and Canada in New York in 1844.', hint: 'Neither of these countries are major Test-playing nations today.' },
    { format: 'mixed', difficulty: 'Hard', question: 'The term "chinaman" is used to describe what type of bowler?', options: ['A left-arm unorthodox spin bowler', 'A right-arm fast bowler', 'A switch-hitting batsman', 'A deep square leg fielder'], correctAnswer: 'A left-arm unorthodox spin bowler', explanation: 'A "chinaman" is a type of delivery bowled by a left-arm slow bowler that spins from off to leg for a right-handed batsman.', hint: 'Think of a bowler like Kuldeep Yadav.' },
    { format: 'mixed', difficulty: 'Hard', question: 'Who was the first player to be given out by a third umpire?', options: ['Jonty Rhodes', 'Sachin Tendulkar', 'Inzamam-ul-Haq', 'Brian Lara'], correctAnswer: 'Sachin Tendulkar', explanation: 'In 1992, Sachin Tendulkar became the first batsman to be given out by a third umpire, run out by a referral in a match against South Africa.', hint: 'This Indian batting legend was the first victim of technology.' },
    { format: 'mixed', difficulty: 'Hard', question: 'The laws of cricket are maintained by which organization?', options: ['ICC', 'MCC', 'ECB', 'BCCI'], correctAnswer: 'MCC', explanation: 'The Marylebone Cricket Club (MCC), based at Lord\'s, is the custodian of the Laws of Cricket.', hint: 'This club is based at the "Home of Cricket", Lord\'s.'},
    { format: 'mixed', difficulty: 'Hard', question: 'What is "Bazball"?', options: ['A brand of cricket bat', 'A type of spin bowling', 'An aggressive style of Test cricket', 'A fielding strategy'], correctAnswer: 'An aggressive style of Test cricket', explanation: '"Bazball" is an informal term for the aggressive, attacking style of Test cricket played by the England team under coach Brendon "Baz" McCullum.', hint: 'It\'s associated with the England Test team and their coach Brendon McCullum.'},
    { format: 'mixed', difficulty: 'Hard', question: 'What does the term "Beamer" refer to?', options: ['A very slow delivery', 'A ball that bounces three times', 'A full toss delivery above waist height', 'A delivery that hits the batsman\'s helmet'], correctAnswer: 'A full toss delivery above waist height', explanation: 'A beamer is an illegal fast, full-toss delivery that is bowled above the batsman\'s waist height. It is dangerous and results in a no-ball.', hint: 'It is considered a dangerous type of delivery.'},
    { format: 'mixed', difficulty: 'Hard', question: 'Which two batsmen were involved in the highest partnership in Test cricket history?', options: ['Sangakkara and Jayawardene', 'Dravid and Laxman', 'Hayden and Langer', 'Lara and Chanderpaul'], correctAnswer: 'Sangakkara and Jayawardene', explanation: 'Mahela Jayawardene and Kumar Sangakkara of Sri Lanka put on a record-breaking partnership of 624 runs against South Africa in 2006.', hint: 'They are two legendary Sri Lankan batsmen.'},
    { format: 'mixed', difficulty: 'Hard', question: 'The "reverse sweep" shot was popularized by which batsman?', options: ['Kevin Pietersen', 'Mike Gatting', 'Andy Flower', 'Javed Miandad'], correctAnswer: 'Mike Gatting', explanation: 'While many have played it since, England\'s Mike Gatting is often credited with popularizing the reverse sweep, famously getting out to it in the 1987 World Cup final.', hint: 'He was an English captain in the 1980s.'},
    { format: 'mixed', difficulty: 'Hard', question: 'What is a "Kookaburra" in cricket terms?', options: ['A type of bat', 'A fielding position', 'A brand of cricket ball', 'A style of bowling'], correctAnswer: 'A brand of cricket ball', explanation: 'Kookaburra is a major Australian manufacturer of cricket balls, used in most ODIs and T20Is, and in Test matches in several countries.', hint: 'This brand is named after an Australian bird.'},
    
    // Very Hard
    { format: 'mixed', difficulty: 'Very Hard', question: 'Who is the only man to have taken a Test hat-trick on his birthday?', options: ['Peter Siddle', 'Irfan Pathan', 'Wasim Akram', 'Shane Warne'], correctAnswer: 'Peter Siddle', explanation: 'Australian fast bowler Peter Siddle took a hat-trick against England at the Gabba on his 26th birthday, November 25, 2010.', hint: 'This Australian fast bowler achieved the feat against England in 2010.'},
    { format: 'mixed', difficulty: 'Very Hard', question: 'Which player has been on the losing side of two 50-over World Cup finals and one T20 World Cup final?', options: ['Kumar Sangakkara', 'Ross Taylor', 'Brendon McCullum', 'Kane Williamson'], correctAnswer: 'Kumar Sangakkara', explanation: 'Sri Lankan legend Kumar Sangakkara was part of the teams that lost the 2007 and 2011 ODI World Cup finals, and the 2012 T20 World Cup final.', hint: 'This Sri Lankan wicket-keeper batsman is a legend of the game.'},
    { format: 'mixed', difficulty: 'Very Hard', question: 'The Duckworth-Lewis method was first used in an international match between which two teams?', options: ['England and Australia', 'South Africa and India', 'Zimbabwe and England', 'Pakistan and Sri Lanka'], correctAnswer: 'Zimbabwe and England', explanation: 'The D/L method was first used in an ODI between Zimbabwe and England in 1996-97, which Zimbabwe won by 7 runs.', hint: 'It involved an African nation and the inventors of the game.'},
    { format: 'mixed', difficulty: 'Very Hard', question: 'Before becoming a cricket umpire, what was Dickie Bird\'s profession?', options: ['Coal miner', 'Bus driver', 'Teacher', 'Police officer'], correctAnswer: 'Coal miner', explanation: 'The legendary English umpire Harold "Dickie" Bird worked as a coal miner before taking up professional cricket and then umpiring.', hint: 'He had a tough, manual-labour job in his youth.'},
    { format: 'mixed', difficulty: 'Very Hard', question: 'Which non-Test playing nation has the most ODI wins against a Test-playing nation?', options: ['Kenya', 'Netherlands', 'Scotland', 'Ireland'], correctAnswer: 'Kenya', explanation: 'Kenya, despite no longer having ODI status, has a number of historic wins against Test nations, most famously reaching the 2003 World Cup semi-finals.', hint: 'This African nation had a dream run in the 2003 World Cup.'},
    
    // Expert
    { format: 'mixed', difficulty: 'Expert', question: 'Who famously "walked" in the 2003 World Cup semi-final despite being given not out?', options: ['Ricky Ponting', 'Sachin Tendulkar', 'Adam Gilchrist', 'Jacques Kallis'], correctAnswer: 'Adam Gilchrist', explanation: 'In a great act of sportsmanship, Australian wicket-keeper batsman Adam Gilchrist walked off the field after edging the ball, even though the umpire had not given him out.', hint: 'This Australian wicketkeeper-batsman was known for his sportsmanship.' },
    { format: 'mixed', difficulty: 'Expert', question: 'Which cricket ball manufacturer produces the ball used for Test matches in England?', options: ['Kookaburra', 'Dukes', 'SG (Sanspareils Greenlands)', 'Gray-Nicolls'], correctAnswer: 'Dukes', explanation: 'Dukes balls are used for Test matches in England and the West Indies and are known for their prominent seam that aids swing bowling.', hint: 'This brand is famously associated with English swing conditions.' },
    { format: 'mixed', difficulty: 'Expert', question: 'The longest Test match in history was played between South Africa and England in 1939. How many days did it last?', options: ['9 days', '10 days', '11 days', '12 days'], correctAnswer: '12 days', explanation: 'The "timeless" Test between South Africa and England in 1939 was played over 12 days, eventually being abandoned as a draw so the English team could catch their boat home.', hint: 'It was a "timeless" test that went on for nearly two weeks.' },
    { format: 'mixed', difficulty: 'Expert', question: 'Who is the only person to have played both international cricket and international football (soccer)?', options: ['Viv Richards', 'C.B. Fry', 'Ellyse Perry', 'Jonty Rhodes'], correctAnswer: 'C.B. Fry', explanation: 'Charles Burgess Fry represented England in both cricket and football, and also equaled the world record for the long jump.', hint: 'This all-round sportsman played for England in the late 19th and early 20th century.'},
    { format: 'mixed', difficulty: 'Expert', question: 'The now-defunct "Timeless Test" had its last match end in a draw because...', options: ['The pitch became too dangerous', 'Both teams agreed to a draw', 'The visiting team had to catch their boat home', 'A war broke out'], correctAnswer: 'The visiting team had to catch their boat home', explanation: 'The final Timeless Test between South Africa and England in 1939 was abandoned after 12 days of play because the English team had to leave to catch their boat back to England.', hint: 'The reason for the draw was related to travel logistics.'},
    { format: 'mixed', difficulty: 'Expert', question: 'Wilfred Rhodes, an English cricketer, played his last Test match at what age?', options: ['45', '48', '52', '55'], correctAnswer: '52', explanation: 'Wilfred Rhodes played his final Test match for England at the age of 52 years and 165 days, making him the oldest person to play Test cricket.', hint: 'He is the oldest player to have ever played a Test match.'},
    { format: 'mixed', difficulty: 'Expert', question: 'Who is the only cricketer to have scored a century and taken a five-wicket haul in the same Test match on a record nine occasions?', options: ['Ian Botham', 'Kapil Dev', 'Shakib Al Hasan', 'Ravichandran Ashwin'], correctAnswer: 'Ian Botham', explanation: 'English all-rounder Sir Ian Botham achieved the rare "match double" of a century and a five-for in the same Test match a record nine times.', hint: 'This legendary English all-rounder was a dominant force in the 1980s.' },
    { format: 'mixed', difficulty: 'Expert', question: 'What is unique about the Test match between South Africa and England at Centurion in 2000?', options: ['It was the shortest Test ever', 'One innings from each side was forfeited to force a result', 'It ended in a tie', 'All 4 innings were declared'], correctAnswer: 'One innings from each side was forfeited to force a result', explanation: 'To create a result in a rain-affected match, captains Hansie Cronje and Nasser Hussain agreed to forfeit an innings each. It was later revealed Cronje was bribed by a bookmaker to ensure a result.', hint: 'This match is infamous for the involvement of Hansie Cronje and bookmakers.'},
    { format: 'mixed', difficulty: 'Expert', question: 'Who was the first bowler to take 10 wickets in a single Test innings?', options: ['Jim Laker', 'Anil Kumble', 'Sydney Barnes', 'George Lohmann'], correctAnswer: 'Jim Laker', explanation: 'England\'s Jim Laker was the first bowler to take all 10 wickets in a Test innings, achieving figures of 10/53 against Australia in 1956.', hint: 'He was an English off-spinner who took 19 wickets in the same match.'},
    { format: 'mixed', difficulty: 'Expert', question: 'The "Sandpapergate" scandal in 2018 involved which three Australian players?', options: ['Warner, Smith, Starc', 'Warner, Smith, Bancroft', 'Finch, Maxwell, Cummins', 'Paine, Lyon, Hazlewood'], correctAnswer: 'Warner, Smith, Bancroft', explanation: 'Cameron Bancroft was caught using sandpaper to alter the ball, with captain Steve Smith and vice-captain David Warner found to be involved in the plan.', hint: 'It involved the captain, vice-captain, and a young opening batsman.'},
    
    // ... more mixed questions ...

    // =================================================================================
    // IPL 
    // =================================================================================
    { format: 'ipl', difficulty: 'Easy', question: 'Which team won the first-ever IPL tournament in 2008?', options: ['Chennai Super Kings', 'Mumbai Indians', 'Kolkata Knight Riders', 'Rajasthan Royals'], correctAnswer: 'Rajasthan Royals', explanation: 'Rajasthan Royals, led by Shane Warne, were the surprise champions of the inaugural IPL season in 2008.', hint: 'This team was led by a legendary Australian spinner.' },
    { format: 'ipl', difficulty: 'Easy', question: 'What is the "Purple Cap" awarded for in the IPL?', options: ['Most wickets', 'Most runs', 'Most sixes', 'Best fair play'], correctAnswer: 'Most wickets', explanation: 'The Purple Cap is awarded to the leading wicket-taker in an edition of the Indian Premier League.', hint: 'It\'s for the bowler who takes the highest number of wickets in the tournament.' },
    // ... more IPL questions ...
    
    // =================================================================================
    // T20
    // =================================================================================
    { format: 't20', difficulty: 'Easy', question: 'How many overs are in a T20 innings?', options: ['10', '20', '50', '90'], correctAnswer: '20', explanation: 'A T20 match consists of two innings, with each innings limited to a maximum of 20 overs.', hint: 'The name of the format gives it away.' },
    { format: 't20', difficulty: 'Medium', question: 'Who hit 6 sixes in an over in the 2007 T20 World Cup?', options: ['Chris Gayle', 'Yuvraj Singh', 'MS Dhoni', 'Adam Gilchrist'], correctAnswer: 'Yuvraj Singh', explanation: 'Yuvraj Singh famously hit England\'s Stuart Broad for six consecutive sixes in an over during the 2007 ICC World T20.', hint: 'This stylish Indian left-hander achieved the feat against England.' },
    // ... more T20 questions ...

    // =================================================================================
    // ODI
    // =================================================================================
    { format: 'odi', difficulty: 'Easy', question: 'How many overs are in a One Day International (ODI) innings?', options: ['20', '40', '50', '100'], correctAnswer: '50', explanation: 'A standard ODI match consists of 50 overs per side.', hint: 'It\'s two and a half times longer than a T20 innings.' },
    // ... more ODI questions ...
    
    // =================================================================================
    // TEST
    // =================================================================================
    { format: 'test', difficulty: 'Easy', question: 'What color of ball is traditionally used in Test cricket?', options: ['White', 'Red', 'Pink', 'Orange'], correctAnswer: 'Red', explanation: 'A red ball is traditionally used for Test matches and first-class cricket played during the day.', hint: 'It\'s the classic color used since the beginning of the sport.' },
    // ... more Test questions ...
    
    // =================================================================================
    // WPL
    // =================================================================================
    { format: 'wpl', difficulty: 'Easy', question: 'Who was the most expensive player in the first WPL auction?', options: ['Ellyse Perry', 'Smriti Mandhana', 'Harmanpreet Kaur', 'Ashleigh Gardner'], correctAnswer: 'Smriti Mandhana', explanation: 'Smriti Mandhana was the most expensive player, bought by Royal Challengers Bangalore for ₹3.4 crore at the inaugural WPL auction.', hint: 'This stylish Indian left-handed opener was bought by RCB.' }
    // ... more WPL questions ...
];


/**
 * Retrieves a fallback quiz from the local array of questions.
 * @param format The cricket format (e.g., 'ipl', 't20').
 * @returns A QuizData object containing 5 questions.
 */
export function getLocalFallbackQuiz(format: string): { questions: QuizDataQuestion[] } {
  const normalizedFormat = format.toLowerCase();
  
  let questionsForFormat = allFallbackQuestions.filter(q => q.format === normalizedFormat);

  if (questionsForFormat.length < 5) {
    console.warn(`Not enough local fallback questions for format "${format}". Using "mixed" format.`);
    questionsForFormat = allFallbackQuestions.filter(q => q.format === 'mixed');
  }

  const shuffledQuestions = shuffleArray(questionsForFormat);
  const selectedQuestions = shuffledQuestions.slice(0, 5).map((q, index) => ({
      ...q,
      id: `local_fb_${normalizedFormat}_${Date.now()}_${index}` 
  }));

  return { questions: selectedQuestions };
}
