/**
 * @fileoverview A global fallback list of engaging cricket facts.
 * This list is used as a tertiary fallback by components when both AI and
 * format-specific fallbacks fail, ensuring content is always available.
 */

export const fallbackFacts: string[] = [
  "Inzamam-ul-Haq once got run out because he stopped to swat a bee instead of running.",
  "Chris Gayle is the only player to hit the very first ball of a Test match for six.",
  "MS Dhoni used to work as a train ticket collector before becoming India’s most successful captain.",
  "Virender Sehwag never liked running singles — he said, “If I see the ball, I hit it.”",
  "Muttiah Muralitharan was once caught smiling even while getting hit for sixes.",
  "Sachin Tendulkar’s first car was a humble Maruti 800.",
  "AB de Villiers was good at so many sports, fans called him “Mr. 360” not just for cricket shots but also for his talents in rugby, tennis, and hockey.",
  "Lasith Malinga’s teammates nicknamed him “Slinga” because of his unique bowling action.",
  "David Warner once celebrated a century with a dance straight out of TikTok.",
  "Sunil Gavaskar once batted wearing ordinary tennis shoes because his cricket shoes were missing.",
  "Shahid Afridi scored the fastest ODI hundred in 1996 using a borrowed bat from Waqar Younis.",
  "The longest cricket match lasted 12 days in 1939 between England and South Africa — and it still ended in a draw!",
  "Jim Laker took all 10 wickets in a Test innings in 1956.",
  "Wilfred Rhodes played Test cricket until the age of 52.",
  "Ishant Sharma has dismissed Alastair Cook most times in Tests (9), earning him the nickname “Cook’s Nightmare.”",
  "Only four players in history have played Tests in four different decades.",
  "India once won a Test match in 2011 without hitting a single six.",
  "In 2014, Rohit Sharma scored 264 runs in an ODI — more than the whole Sri Lankan team that day!",
  "Don Bradman once scored 309 runs in a single day of Test cricket.",
  "Andrew Flintoff once celebrated a wicket by doing a “starfish” dive on the pitch.",
  "Kieron Pollard once pretended to tape his mouth shut after being warned for talking too much.",
  "MS Dhoni once stopped a press conference mid-way because his phone started ringing.",
  "Sourav Ganguly famously waved his shirt from the Lord’s balcony after winning the 2002 NatWest final.",
  "Yuvraj Singh once hit six sixes in a T20 match after being sledged by Andrew Flintoff.",
  "A dog once ran onto the field in the middle of an India-Sri Lanka match and delayed play.",
  "Glenn Maxwell was once bowled after the ball deflected off his own shoelaces.",
  "In 1977, Kerry Packer’s World Series players wore pajamas, giving birth to “colored clothing” cricket.",
  "Kumar Sangakkara once sang a song on stage at the ICC awards.",
  "Shane Warne once missed a Test because he was bitten by a mosquito and had food poisoning.",
  "A batsman can be given out “obstructing the field” if he deliberately blocks a throw.",
  "In 2001, Virender Sehwag became the first batsman in ODI history to be dismissed for handling the ball.",
  "A cricket ball has 6 rows of stitches and weighs between 155.9 and 163 grams.",
  "In 2013, a match in South Africa was paused because of a swarm of bees.",
  "Chris Gayle once got fined for jokingly asking a reporter out on live TV.",
  "A bowler can legally bowl with both hands — but must inform the umpire first.",
  "During the 1992 World Cup, players wore colored kits for the first time ever.",
  "Adam Gilchrist once walked off even though the umpire didn’t give him out — surprising everyone.",
  "Steve Smith used to shadow bat in hotel rooms even without a bat.",
  "The first recorded “Mankading” was in 1947 by Vinoo Mankad.",
  "In Eden Gardens, Kolkata, crowds can be louder than a jet engine.",
  "In 1999, a fan invaded the pitch wearing just underwear during an England match.",
  "In 2016, a match in Bangalore was delayed because a snake was found on the outfield.",
  "The Barmy Army (England fans) are famous for singing hilarious songs to tease players.",
  "Once, Indian fans lit candles outside Anil Kumble’s house after he bowled with a broken jaw.",
  "In the IPL, RCB fans shout “Ee Sala Cup Namde” every season, but the team hasn’t won yet.",
  "A match in Sharjah was stopped because sandstorms made it impossible to see the ball.",
  "Pakistani fans once rode on camels to celebrate a victory against India.",
  "In New Zealand, fans often dress up as bananas, chickens, or superheroes in the crowd.",
  "At the SCG, fans once carried giant inflatable beach balls into the stands.",
  "Sachin Tendulkar faced over 70 different debutants during his career.",
  "Muttiah Muralitharan has more Test wickets than the entire Zimbabwe team combined.",
  "Ricky Ponting has been run out more than any other player in ODIs.",
  "Virat Kohli averages more in successful chases than in first innings.",
  "Jacques Kallis has more Test centuries than Brian Lara.",
  "Chris Gayle has hit more sixes in international cricket than many teams combined.",
  "MS Dhoni is the only captain to win all three ICC white-ball trophies.",
  "The shortest Test match lasted less than 6 hours (Australia vs South Africa, 1932).",
  "Shoaib Akhtar bowled the fastest ball ever at 161.3 km/h.",
  "Brian Lara has the highest individual score in first-class cricket: 501*.",
  "Umpires once wore white coats and ties in Test matches.",
  "The term “hat-trick” came from a bowler being given a hat for 3 wickets in 3 balls.",
  "A cricket bat can have up to 10 grains of wood.",
  "The longest six in cricket history (153 meters) was hit by Shahid Afridi.",
  "South Africa once lost a World Cup semi-final because they misunderstood the rain rule.",
  "In Test cricket, players sometimes wear woolen sweaters in blazing summer.",
  "Dennis Lillee once came out to bat with an aluminum bat.",
  "Chris Gayle owns a special gold T20 bat.",
  "Yuzvendra Chahal once fainted on the ground due to extreme heat.",
  "Rishabh Pant once played an entire innings humming Bollywood songs loudly.",
  "The Ashes urn is just 11 cm tall.",
  "Australia once dismissed England for just 45 runs in a Test.",
  "Allan Border once fielded for India as a substitute fielder.",
  "The first recorded cricket match was played in 1646.",
  "In 1935, a cricket ball killed a batsman after hitting him in the chest.",
  "The first IPL was won by Rajasthan Royals.",
  "Virat Kohli was once caught sledging in Hindi, not realizing the stump mic picked it up.",
  "Umpire Dickie Bird was so popular that fans asked for his autograph mid-match.",
  "In 2012, Kevin Pietersen was dropped from the England team for texting the opposition.",
  "Yuvraj Singh once said he thought T20 cricket wouldn’t last long.",
  "MS Dhoni once gifted his World Cup-winning bat to charity — it was auctioned for $161,000.",
  "Sachin Tendulkar was a ball boy during the 1987 World Cup.",
  "In 2007, India played a T20 match where they had to bowl with 7 different bowlers in one over due to confusion.",
  "Glenn McGrath once scored 61 runs in a Test innings, shocking everyone.",
  "India’s first Test win abroad came after 20 years of playing cricket.",
  "Shoaib Akhtar once accidentally bowled a beamer that broke a batter’s helmet in half.",
  "Sreesanth once danced on the field after hitting Andre Nel for a six.",
  "Brett Lee released a Bollywood song with Asha Bhosle.",
  "Sachin Tendulkar used a bat so heavy that most players couldn’t even lift it.",
  "Brendon McCullum scored 158 in the very first IPL match ever.",
  "Kumble once bowled with a broken jaw and still took wickets.",
  "Kevin O’Brien scored the fastest World Cup century in 50 balls.",
  "Herschelle Gibbs once hit six sixes in an over in a World Cup match.",
  "Rahul Dravid was nicknamed “The Wall” because he almost never got out early.",
  "Indian spinner B. S. Chandrasekhar took wickets with a polio-affected arm.",
  "Shoaib Akhtar was nicknamed “The Rawalpindi Express” after a local train.",
  "Lasith Malinga once took four wickets in four balls.",
  "Kapil Dev once hit four consecutive sixes to save India from follow-on.",
  "Virat Kohli loves chasing so much that his teammates call him “Chase Master.”",
  "The first-ever cricket ball was made of wool, not leather.",
];
