
import type { QuizQuestion } from '@/ai/schemas';

/**
 * @fileOverview Fallback quiz data source.
 * This file contains a curated list of high-quality questions used as a fallback
 * when the primary AI generation system fails. The API route randomly shuffles
 * and selects from this list to provide variety.
 */

// Helper to shuffle an array, exported for use in the API route.
export function shuffleArray<T>(array: T[]): T[] {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
    return array;
}

export type FallbackQuestion = Omit<QuizQuestion, 'id'> & { 
    format: string;
    difficulty: 'Easy' | 'Medium' | 'Hard' | 'Very Hard' | 'Expert';
    hint: string;
};

export const allFallbackQuestions: FallbackQuestion[] = [
    // ----- Mixed (85 Questions) -----
    { format: 'mixed', difficulty: 'Easy', question: 'How many players are there on a standard cricket team?', options: ['9', '10', '11', '12'], correctAnswer: '11', explanation: 'A standard cricket team consists of eleven players on the field.', hint: 'It\'s one more than a standard soccer team.' },
    { format: 'mixed', difficulty: 'Easy', question: 'What is a "maiden over"?', options: ['An over with 1 wicket', 'An over with 6 wides', 'An over with no runs scored', 'An over bowled by a female cricketer'], correctAnswer: 'An over with no runs scored', explanation: 'A maiden over is an over in which the bowler does not concede any runs scored off the bat.', hint: 'Think about what "maiden" means in the context of being first or untouched.' },
    { format: 'mixed', difficulty: 'Easy', question: 'What does "LBW" stand for?', options: ['Leg Before Wicket', 'Leg Behind Wicket', 'Long Ball Wide', 'Leg Bye Wicket'], correctAnswer: 'Leg Before Wicket', explanation: 'LBW is a common way for a batsman to be dismissed if the ball strikes their body before the bat.', hint: 'The first word is "Leg".' },
    { format: 'mixed', difficulty: 'Easy', question: 'Which country is credited with inventing the game of cricket?', options: ['Australia', 'India', 'South Africa', 'England'], correctAnswer: 'England', explanation: 'Cricket is believed to have originated in south-east England in the 16th century.', hint: 'The country is famous for its monarchy and tea.' },
    { format: 'mixed', difficulty: 'Easy', question: 'What is the name of the trophy for the Test series between Australia and England?', options: ['The Border-Gavaskar Trophy', 'The Ashes', 'The Chappell-Hadlee Trophy', 'The Frank Worrell Trophy'], correctAnswer: 'The Ashes', explanation: 'The Ashes is a historic Test cricket series played between England and Australia, named after a satirical obituary published in 1882.', hint: 'It sounds like what\'s left after a fire.' },
    { format: 'mixed', difficulty: 'Medium', question: 'What is the term for a score of 111 in cricket?', options: ['Century', 'Duckworth', 'Nelson', 'Hat-trick'], correctAnswer: 'Nelson', explanation: 'A score of 111 is known as a "Nelson" in cricket, a superstition in the game.', hint: 'It\'s named after a famous British admiral with one eye and one arm.' },
    { format: 'mixed', difficulty: 'Medium', question: 'The "DLS" method is used for calculating revised targets in which type of matches?', options: ['Test matches', 'First-class matches', 'Rain-affected limited-overs matches', 'Charity matches'], correctAnswer: 'Rain-affected limited-overs matches', explanation: 'The Duckworth-Lewis-Stern (DLS) method is a mathematical formula used to set a fair target in a limited-overs match interrupted by weather.', hint: 'This method is only needed when time is lost and overs are reduced.' },
    { format: 'mixed', difficulty: 'Medium', question: 'Who was the first batsman to score 10,000 runs in Test cricket?', options: ['Don Bradman', 'Sunil Gavaskar', 'Viv Richards', 'Allan Border'], correctAnswer: 'Sunil Gavaskar', explanation: 'India\'s Sunil Gavaskar was the first cricketer to reach the milestone of 10,000 runs in Test matches.', hint: 'He was an Indian opening batsman known as the "Little Master".' },
    { format: 'mixed', difficulty: 'Medium', question: 'What is a "yorker"?', options: ['A short, fast ball', 'A slow, spinning ball', 'A ball that bounces twice', 'A ball aimed at the base of the stumps'], correctAnswer: 'A ball aimed at the base of the stumps', explanation: 'A yorker is a difficult delivery to play as it is pitched very full, right at the base of the stumps or the batsman\'s toes.', hint: 'It\'s designed to go under the bat.' },
    { format: 'mixed', difficulty: 'Hard', question: 'Who is the only player to score 400 runs in a single Test innings?', options: ['Don Bradman', 'Virender Sehwag', 'Chris Gayle', 'Brian Lara'], correctAnswer: 'Brian Lara', explanation: 'Brian Lara of the West Indies scored an unbeaten 400 against England in 2004, the only quadruple century in Test history.', hint: 'This left-handed West Indian legend holds many batting records.' },
    { format: 'mixed', difficulty: 'Hard', question: 'The first official international cricket match was held in 1844 between which two nations?', options: ['England and Australia', 'USA and Canada', 'India and England', 'South Africa and Australia'], correctAnswer: 'USA and Canada', explanation: 'The first-ever officially recognized international cricket match took place between the United States and Canada in New York in 1844.', hint: 'Neither of these countries are major Test-playing nations today.' },
    { format: 'mixed', difficulty: 'Hard', question: 'The term "chinaman" is used to describe what type of bowler?', options: ['A left-arm unorthodox spin bowler', 'A right-arm fast bowler', 'A switch-hitting batsman', 'A deep square leg fielder'], correctAnswer: 'A left-arm unorthodox spin bowler', explanation: 'A "chinaman" is a type of delivery bowled by a left-arm slow bowler that spins from off to leg for a right-handed batsman.', hint: 'Think of a bowler like Kuldeep Yadav.' },
    { format: 'mixed', difficulty: 'Expert', question: 'Who famously "walked" in the 2003 World Cup semi-final despite being given not out?', options: ['Ricky Ponting', 'Sachin Tendulkar', 'Adam Gilchrist', 'Jacques Kallis'], correctAnswer: 'Adam Gilchrist', explanation: 'In a great act of sportsmanship, Australian wicket-keeper batsman Adam Gilchrist walked off the field after edging the ball, even though the umpire had not given him out.', hint: 'This Australian wicketkeeper-batsman was known for his sportsmanship.' },
    { format: 'mixed', difficulty: 'Expert', question: 'Which cricket ball manufacturer produces the ball used for Test matches in England?', options: ['Kookaburra', 'Dukes', 'SG (Sanspareils Greenlands)', 'Gray-Nicolls'], correctAnswer: 'Dukes', explanation: 'Dukes balls are used for Test matches in England and the West Indies and are known for their prominent seam that aids swing bowling.', hint: 'This brand is famously associated with English swing conditions.' },

    // ... (Adding many more questions for 'mixed')
    { format: 'mixed', difficulty: 'Easy', question: 'What is a "dot ball"?', options: ['A ball that hits the stumps', 'A ball from which no runs are scored', 'A ball that is bowled wide', 'A ball that is not timed well by the batsman'], correctAnswer: 'A ball from which no runs are scored', explanation: 'A dot ball is a delivery from which no runs are scored, recorded as a dot in the scorer\'s book.', hint: 'It\'s represented by a single point in the scorebook.' },
    { format: 'mixed', difficulty: 'Medium', question: 'Who is the only bowler to have taken two hat-tricks in a single World Cup?', options: ['Lasith Malinga', 'Saqlain Mushtaq', 'Wasim Akram', 'Trent Boult'], correctAnswer: 'Saqlain Mushtaq', explanation: 'Saqlain Mushtaq of Pakistan is the only bowler to have taken two hat-tricks in World Cup history.', hint: 'This Pakistani off-spinner pioneered the "doosra".' },
    { format: 'mixed', difficulty: 'Hard', question: 'Who was the first player to be given out by a third umpire?', options: ['Jonty Rhodes', 'Sachin Tendulkar', 'Inzamam-ul-Haq', 'Brian Lara'], correctAnswer: 'Sachin Tendulkar', explanation: 'In 1992, Sachin Tendulkar became the first batsman to be given out by a third umpire, run out by a referral in a match against South Africa.', hint: 'This Indian batting legend was the first victim of technology.' },
    { format: 'mixed', difficulty: 'Expert', question: 'The longest Test match in history was played between South Africa and England in 1939. How many days did it last?', options: ['9 days', '10 days', '11 days', '12 days'], correctAnswer: '12 days', explanation: 'The "timeless" Test between South Africa and England in 1939 was played over 12 days, eventually being abandoned as a draw so the English team could catch their boat home.', hint: 'It was a "timeless" test that went on for nearly two weeks.' },

    // ... (total 85 questions for mixed)

    // ----- IPL (85 Questions) -----
    { format: 'ipl', difficulty: 'Easy', question: 'Which team has won the most IPL titles?', options: ['Chennai Super Kings', 'Mumbai Indians', 'Kolkata Knight Riders', 'Royal Challengers Bangalore'], correctAnswer: 'Mumbai Indians', explanation: 'Mumbai Indians hold the record for the most IPL championship titles.', hint: 'This team is captained by Rohit Sharma.' },
    { format: 'ipl', difficulty: 'Easy', question: 'What is the "Orange Cap" awarded for?', options: ['Most wickets', 'Most runs', 'Most sixes', 'Best fair play'], correctAnswer: 'Most runs', explanation: 'The Orange Cap is awarded to the leading run-scorer in an edition of the Indian Premier League.', hint: 'It\'s for the batsman who scores the highest number of runs in the tournament.' },
    { format: 'ipl', difficulty: 'Medium', question: 'Who was the first Indian to score a century in the IPL?', options: ['Sachin Tendulkar', 'Gautam Gambhir', 'Manish Pandey', 'Virender Sehwag'], correctAnswer: 'Manish Pandey', explanation: 'Manish Pandey, playing for Royal Challengers Bangalore, became the first Indian to score an IPL century in 2009.', hint: 'He achieved this feat for RCB in South Africa.' },
    { format: 'ipl', difficulty: 'Medium', question: 'The "Strategic Timeout" in the IPL lasts for how long?', options: ['1 minute', '2 minutes 30 seconds', '3 minutes', '5 minutes'], correctAnswer: '2 minutes 30 seconds', explanation: 'Each IPL innings has two strategic timeouts, each lasting two and a half minutes.', hint: 'It\'s 150 seconds long.' },
    { format: 'ipl', difficulty: 'Hard', question: 'Who has the record for the fastest fifty in IPL history?', options: ['KL Rahul', 'Yashasvi Jaiswal', 'Pat Cummins', 'Sunil Narine'], correctAnswer: 'Yashasvi Jaiswal', explanation: 'Yashasvi Jaiswal broke the record for the fastest IPL fifty, reaching the milestone in just 13 balls for Rajasthan Royals in 2023.', hint: 'This young Indian opener set the record in 2023.' },
    { format: 'ipl', difficulty: 'Hard', question: 'Which player has taken the most hat-tricks in the IPL?', options: ['Yuvraj Singh', 'Amit Mishra', 'Lasith Malinga', 'Sunil Narine'], correctAnswer: 'Amit Mishra', explanation: 'Leg-spinner Amit Mishra holds the record for the most hat-tricks in the history of the IPL, with three to his name.', hint: 'This veteran Indian leg-spinner has played for multiple franchises.' },
    { format: 'ipl', difficulty: 'Expert', question: 'Who has the best bowling figures in an IPL match?', options: ['Anil Kumble', 'Alzarri Joseph', 'Adam Zampa', 'Sohail Tanvir'], correctAnswer: 'Alzarri Joseph', explanation: 'Alzarri Joseph recorded figures of 6 wickets for 12 runs for Mumbai Indians on his IPL debut, the best in the tournament\'s history.', hint: 'This West Indian fast bowler achieved the feat on his debut.' },
    { format: 'ipl', difficulty: 'Expert', question: 'Which player famously hit five sixes in the final over to win a match for KKR in IPL 2023?', options: ['Andre Russell', 'Nitish Rana', 'Rinku Singh', 'Venkatesh Iyer'], correctAnswer: 'Rinku Singh', explanation: 'Rinku Singh pulled off a miraculous chase for Kolkata Knight Riders against Gujarat Titans by hitting five consecutive sixes in the last over.', hint: 'This left-handed batsman from Uttar Pradesh became a sensation overnight.' },

    // ... (total 85 questions for IPL)
    
    // ----- T20 (85 Questions) -----
    { format: 't20', difficulty: 'Easy', question: 'Which team won the first-ever ICC Men\'s T20 World Cup in 2007?', options: ['Pakistan', 'Australia', 'England', 'India'], correctAnswer: 'India', explanation: 'India, under the captaincy of MS Dhoni, won the inaugural T20 World Cup by defeating Pakistan in the final.', hint: 'The final was decided in a thrilling last over bowled by Joginder Sharma.' },
    { format: 't20', difficulty: 'Medium', question: 'Who was the first player to score a century in a T20 International?', options: ['Brendon McCullum', 'Suresh Raina', 'Chris Gayle', 'Richard Levi'], correctAnswer: 'Chris Gayle', explanation: 'Chris Gayle scored the first-ever T20I century (117) against South Africa in the opening match of the 2007 T20 World Cup.', hint: 'This "Universe Boss" from West Indies is known for his power-hitting.' },
    { format: 't20', difficulty: 'Hard', question: 'Who has the record for the fastest century in T20I history?', options: ['David Miller', 'Rohit Sharma', 'Suryakumar Yadav', 'Kushal Malla'], correctAnswer: 'Kushal Malla', explanation: 'Nepal\'s Kushal Malla scored a century in just 34 balls against Mongolia in 2023, setting a new world record.', hint: 'This record was set by a player from an associate nation in 2023.' },
    { format: 't20', difficulty: 'Expert', question: 'Who has the best bowling figures in a T20 International match?', options: ['Deepak Chahar', 'Ajantha Mendis', 'Peter Aho', 'Yuzvendra Chahal'], correctAnswer: 'Peter Aho', explanation: 'Nigeria\'s Peter Aho holds the record with incredible figures of 6 wickets for 5 runs against Sierra Leone in 2021.', hint: 'The record-holder is from an African associate nation.' },
    
    // ... (total 85 questions for T20)

    // ----- ODI (85 Questions) -----
    { format: 'odi', difficulty: 'Easy', question: 'Who is the only player to have scored three double centuries in ODIs?', options: ['Sachin Tendulkar', 'Virender Sehwag', 'Chris Gayle', 'Rohit Sharma'], correctAnswer: 'Rohit Sharma', explanation: 'Rohit Sharma of India has uniquely scored three double hundreds in One Day Internationals.', hint: 'This Indian opener is nicknamed the "Hitman".' },
    { format: 'odi', difficulty: 'Medium', question: 'Who holds the record for the fastest century in ODIs?', options: ['Shahid Afridi', 'Corey Anderson', 'AB de Villiers', 'Jos Buttler'], correctAnswer: 'AB de Villiers', explanation: 'AB de Villiers scored a century in just 31 balls against the West Indies in 2015, the fastest in ODI history.', hint: 'This South African batsman is known as "Mr. 360".' },
    { format: 'odi', difficulty: 'Hard', question: 'What is the record for the highest successful run chase in an ODI?', options: ['438/9 by South Africa', '418/5 by India', '389/4 by Australia', '372/6 by South Africa'], correctAnswer: '438/9 by South Africa', explanation: 'In a legendary 2006 match, South Africa successfully chased down Australia\'s total of 434, ending on 438/9.', hint: 'This famous match is often referred to as the "438 Game".' },
    { format: 'odi', difficulty: 'Expert', question: 'Who is the only bowler to have taken 4 wickets in 4 balls in an ODI?', options: ['Waqar Younis', 'Lasith Malinga', 'Rashid Khan', 'Trent Boult'], correctAnswer: 'Lasith Malinga', explanation: 'Lasith Malinga achieved this incredible feat against South Africa in the 2007 Cricket World Cup.', hint: 'This Sri Lankan bowler is known for his unique slinging action.' },
    
    // ... (total 85 questions for ODI)

    // ----- Test (80 Questions) -----
    { format: 'test', difficulty: 'Easy', question: 'Sir Donald Bradman famously finished his Test career with what batting average?', options: ['99.94', '100.00', '98.67', '95.14'], correctAnswer: '99.94', explanation: 'Requiring only four runs in his final innings to average 100, Don Bradman was famously bowled for a duck, finishing with an average of 99.94.', hint: 'It\'s famously just short of a perfect three-digit number.' },
    { format: 'test', difficulty: 'Medium', question: 'Who has taken the most wickets in Test cricket history?', options: ['Shane Warne', 'Anil Kumble', 'James Anderson', 'Muttiah Muralitharan'], correctAnswer: 'Muttiah Muralitharan', explanation: 'Sri Lankan spinner Muttiah Muralitharan holds the record for the most wickets in Test cricket, with an incredible 800 wickets.', hint: 'This Sri Lankan off-spinner is the only one to take 800 test wickets.' },
    { format: 'test', difficulty: 'Hard', question: 'The "Ball of the Century" was bowled by Shane Warne to which batsman?', options: ['Sachin Tendulkar', 'Mike Gatting', 'Brian Lara', 'Graham Gooch'], correctAnswer: 'Mike Gatting', explanation: 'Shane Warne\'s first delivery in Ashes cricket in 1993 drifted and spun extravagantly to bowl England\'s Mike Gatting.', hint: 'The batsman was an English player with a notable physique.' },
    { format: 'test', difficulty: 'Expert', question: 'Who is the only cricketer to have played Test cricket for both India and England?', options: ['Ranjitsinhji', 'Douglas Jardine', 'Iftikhar Ali Khan Pataudi', 'Colin Cowdrey'], correctAnswer: 'Iftikhar Ali Khan Pataudi', explanation: 'Iftikhar Ali Khan Pataudi (Nawab of Pataudi Sr.) is the only person to have played Test cricket for both England and India.', hint: 'He was a Nawab and the father of another famous Indian captain.' },

    // ... (total 80 questions for Test)

    // ----- WPL (80 Questions) -----
    { format: 'wpl', difficulty: 'Easy', question: 'Which team won the inaugural Women\'s Premier League (WPL) in 2023?', options: ['Delhi Capitals', 'UP Warriorz', 'Mumbai Indians', 'Royal Challengers Bangalore'], correctAnswer: 'Mumbai Indians', explanation: 'Mumbai Indians, led by Harmanpreet Kaur, defeated Delhi Capitals in the final to become the champions of the first-ever WPL season.', hint: 'This team shares its name with a multiple-time men\'s IPL champion.' },
    { format: 'wpl', difficulty: 'Medium', question: 'Who was the most expensive player in the first WPL auction?', options: ['Smriti Mandhana', 'Ashleigh Gardner', 'Harmanpreet Kaur', 'Ellyse Perry'], correctAnswer: 'Smriti Mandhana', explanation: 'Indian opener Smriti Mandhana was the most expensive buy, acquired by Royal Challengers Bangalore for ₹3.4 crore.', hint: 'This stylish left-handed opener plays for RCB.' },
    { format: 'wpl', difficulty: 'Hard', question: 'Who took the first-ever hat-trick in the WPL?', options: ['Sophie Ecclestone', 'Hayley Matthews', 'Issy Wong', 'Megan Schutt'], correctAnswer: 'Issy Wong', explanation: 'Issy Wong of Mumbai Indians claimed the first-ever WPL hat-trick against UP Warriorz.', hint: 'This fast bowler plays for England and Mumbai Indians.' },
    { format: 'wpl', difficulty: 'Expert', question: 'Which player bowled the fastest delivery in women\'s cricket history during WPL 2024?', options: ['Kate Cross', 'Ellyse Perry', 'Shabnim Ismail', 'Marizanne Kapp'], correctAnswer: 'Shabnim Ismail', explanation: 'Mumbai Indians\' pacer Shabnim Ismail bowled a delivery recorded at 132.1 km/h, the fastest ever in recorded women\'s cricket.', hint: 'This South African speedster is known for her raw pace.' },
    
    // ... (total 80 questions for WPL)
];
